# Generated by Django 3.2.8 on 2022-07-25 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0005_auto_20220722_0936'),
        ('equipements', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accessoires',
            new_name='Accessoire',
        ),
        migrations.RenameModel(
            old_name='Materiels',
            new_name='Materiel',
        ),
    ]
