# Generated by Django 3.2.8 on 2022-07-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0002_auto_20220725_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
