# Generated by Django 3.2.8 on 2022-08-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0003_alter_materiel_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='etat',
            field=models.CharField(choices=[('FONCTIONNELLE', 'FONCTIONNELLE'), ('ENDOMMAGE', 'ENDOMMAGE'), ('REPARATION', 'REPARATION'), ('ATTRIBUER', 'ATTRIBUER')], default='', max_length=255),
        ),
    ]
