# Generated by Django 3.2.8 on 2022-07-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engins',
            name='etat',
            field=models.CharField(choices=[('DISPONIBLE', 'DISPONIBLE'), ('OCCUPE', 'OCCUPE'), ('VENDU', 'VENDU'), ('GARAGE', 'GARAGE')], default='', max_length=100),
        ),
    ]
