# Generated by Django 3.2.8 on 2022-07-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engins', '0002_alter_engins_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engins',
            name='numcharsis',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
