# Generated by Django 3.2.8 on 2022-07-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0004_alter_fonction_libelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_materiel',
            name='libelle',
            field=models.CharField(max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name='type_vehicule',
            name='libelle',
            field=models.CharField(max_length=225, unique=True),
        ),
    ]
