# Generated by Django 3.2.8 on 2022-07-25 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametres', '0005_auto_20220722_0936'),
        ('equipements', '0002_auto_20220725_0956'),
        ('engins', '0002_alter_engins_etat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_attribution', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(max_length=255)),
                ('depart', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('date_course', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=100)),
                ('matricule', models.CharField(max_length=255)),
                ('etat', models.CharField(choices=[('ACTIF', 'EN ACTIVITE'), ('DESACTIVE', 'DESACTIVE')], default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fonction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.fonction')),
                ('materiel', models.ManyToManyField(through='gestions.Attribution', to='equipements.Materiel')),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigle', models.CharField(max_length=255)),
                ('titre', models.CharField(max_length=255)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('etat', models.CharField(choices=[('ACTIF', 'EN COURS'), ('DESACTIVE', 'TERMINER')], default='', max_length=255)),
                ('logo_partenaire', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('logo_sarl', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestions.employer')),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=255)),
                ('localite', models.CharField(max_length=255)),
                ('matriculeLouer', models.CharField(blank=True, max_length=255, null=True)),
                ('concessionnaire', models.CharField(blank=True, max_length=255, null=True)),
                ('date_depart', models.DateField()),
                ('date_retour', models.DateField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestions.course')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestions.employer')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestions.projet')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestions.employer'),
        ),
        migrations.AddField(
            model_name='course',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engins.engins'),
        ),
        migrations.AddField(
            model_name='attribution',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestions.employer'),
        ),
        migrations.AddField(
            model_name='attribution',
            name='materiel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipements.materiel'),
        ),
    ]
