# Generated by Django 3.2.8 on 2022-07-25 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='employe',
        ),
    ]
