# Generated by Django 3.2.8 on 2022-07-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestions', '0003_auto_20220725_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='etat',
            field=models.CharField(choices=[('EN ACTIVITE', 'EN ACTIVITE'), ('DESACTIVE', 'DESACTIVE')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='projet',
            name='etat',
            field=models.CharField(choices=[('EN COURS', 'EN COURS'), ('TERMINER', 'TERMINER')], default='', max_length=255),
        ),
    ]
