# Generated by Django 3.2.8 on 2022-07-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestions', '0004_auto_20220726_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='etat_course',
            field=models.CharField(choices=[('EN COURS', 'EN COURS'), ('TERMINER', 'TERMINER')], default='', max_length=255),
        ),
    ]
