# Generated by Django 3.2.8 on 2022-07-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestions', '0005_auto_20220726_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='motif',
            field=models.TextField(),
        ),
    ]
