# Generated by Django 3.2.8 on 2022-07-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestions', '0006_alter_course_motif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='etat',
            field=models.CharField(choices=[('EN ACTIVITE', 'EN ACTIVITE'), ('OCCUPE', 'OCCUPE'), ('DESACTIVE', 'DESACTIVE')], default='', max_length=50),
        ),
    ]
