# Generated by Django 3.2.8 on 2022-07-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestions', '0007_alter_employer_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='etat_mission',
            field=models.CharField(choices=[('EN COURS', 'EN COURS'), ('TERMINER', 'TERMINER')], default='', max_length=255),
        ),
    ]
