# Generated by Django 3.2.8 on 2022-07-27 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestions', '0008_mission_etat_mission'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
