# Generated by Django 3.2.8 on 2022-07-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestions', '0009_auto_20220727_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='moyentransport',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
