# Generated by Django 3.2.8 on 2022-08-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestions', '0010_mission_moyentransport'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribution',
            name='etat',
            field=models.BooleanField(default=False),
        ),
    ]
