# Generated by Django 3.2.8 on 2022-08-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestions', '0012_mission_date_terminer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='date_terminer',
            field=models.DateField(blank=True, null=True),
        ),
    ]
